version: '3'
services:
  mdw:
    hostname: mdw
    image: "kypdb6"
    ports:
     - "6222:22"
     - "6432:5432"
     - "19001:19001"
  sdw1:
    hostname: sdw1
    image: "kypdb6"
  sdw2:
    hostname: sdw2
    image: "kypdb6"
  sdw3:
    hostname: sdw3
    image: "kypdb6"
